import { UserProfile, DailyMission, ATSScanResult, JobApplication, OneClickPack, CountryMigrationInfo } from '../types';

export const mockUser: UserProfile = {
  id: 'usr_789012',
  name: 'Alex Morgan',
  email: 'alex.morgan@careeros.app',
  targetRole: 'Senior Full Stack Engineer',
  careerScore: 785,
  streakCount: 9,
  subscriptionTier: 'PREMIUM',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

export const initialMissions: DailyMission[] = [
  {
    id: 'm1',
    title: 'Apply to 5 High-Match Jobs',
    description: 'Target roles in Germany or Netherlands with >80% ATS match.',
    category: 'APPLY',
    points: 50,
    isCompleted: true,
  },
  {
    id: 'm2',
    title: 'Improve ATS Score by 10%',
    description: 'Add missing keywords: "Docker", "GraphQL", and "Jest" to Master Resume.',
    category: 'ATS',
    points: 100,
    isCompleted: false,
  },
  {
    id: 'm3',
    title: 'Complete 1 AI Interview Simulation',
    description: 'Simulate System Design & React 19 Voice Mock Session.',
    category: 'INTERVIEW',
    points: 75,
    isCompleted: false,
  },
  {
    id: 'm4',
    title: 'Optimize LinkedIn Headline',
    description: 'Incorporate high-search frequency recruiter terms.',
    category: 'LINKEDIN',
    points: 40,
    isCompleted: true,
  },
];

export const sampleATSScan: ATSScanResult = {
  atsScore: 82,
  targetRole: 'Senior Full Stack Engineer',
  matchingKeywords: ['TypeScript', 'Next.js', 'React 19', 'Python', 'Django', 'PostgreSQL', 'Tailwind CSS'],
  missingKeywords: ['Docker', 'Redis', 'Celery', 'AWS S3', 'GraphQL', 'Microservices', 'Kubernetes'],
  formattingScore: 95,
  suggestions: [
    'Add a dedicated "Cloud & DevOps" sub-section under Technical Skills.',
    'Quantify impact in bullet points (e.g., "Improved page load by 40%").',
    'Include "Celery" and "Redis" background task architecture experience.',
  ],
  heatmap: [
    { keyword: 'TypeScript', countInResume: 5, expectedCount: 4 },
    { keyword: 'React', countInResume: 8, expectedCount: 6 },
    { keyword: 'Next.js', countInResume: 4, expectedCount: 3 },
    { keyword: 'Docker', countInResume: 0, expectedCount: 2 },
    { keyword: 'Kubernetes', countInResume: 0, expectedCount: 2 },
    { keyword: 'PostgreSQL', countInResume: 3, expectedCount: 2 },
  ],
};

export const sampleApplications: JobApplication[] = [
  {
    id: 'app_1',
    companyName: 'Spotify',
    jobTitle: 'Senior Full Stack Engineer',
    location: 'Stockholm, Sweden / Remote',
    country: 'Sweden',
    salary: '€75,000 - €90,000',
    stage: 'INTERVIEW',
    appliedDate: '2026-08-01',
    jobUrl: 'https://spotify.jobs/engineer',
  },
  {
    id: 'app_2',
    companyName: 'Zalando',
    jobTitle: 'Lead Frontend Developer',
    location: 'Berlin, Germany',
    country: 'Germany',
    salary: '€85,000 - €95,000',
    stage: 'APPLIED',
    appliedDate: '2026-08-05',
    jobUrl: 'https://zalando.jobs/berlin',
  },
  {
    id: 'app_3',
    companyName: 'Klarna',
    jobTitle: 'Backend Python Architect',
    location: 'Amsterdam, Netherlands',
    country: 'Netherlands',
    salary: '€90,000 - €105,000',
    stage: 'OFFER',
    appliedDate: '2026-07-20',
  },
  {
    id: 'app_4',
    companyName: 'Bolt',
    jobTitle: 'Senior React Developer',
    location: 'Warsaw, Poland',
    country: 'Poland',
    salary: 'PLN 24,000 - 30,000 / mo',
    stage: 'REJECTED',
    appliedDate: '2026-07-15',
    rejectionReason: 'MISSING_KEYWORDS',
  },
  {
    id: 'app_5',
    companyName: 'Revolut',
    jobTitle: 'Full Stack Engineer',
    location: 'Vilnius, Lithuania',
    country: 'Lithuania',
    salary: '€60,000 - €72,000',
    stage: 'REJECTED',
    appliedDate: '2026-07-10',
    rejectionReason: 'VISA_ISSUE',
  },
];

export const countryMigrationData: CountryMigrationInfo[] = [
  {
    country: 'Germany',
    flag: '🇩🇪',
    eligibilityScore: 88,
    visaPathway: 'EU Blue Card / Opportunity Card',
    avgSalaryEUR: '€70,000 - €95,000',
    costOfLivingIndex: 68,
    processingTimeMonths: 2,
    sponsorshipProbability: 'High',
    topDemandRoles: ['Full Stack Engineer', 'DevOps Specialist', 'AI/ML Architect'],
  },
  {
    country: 'Poland',
    flag: '🇵🇱',
    eligibilityScore: 94,
    visaPathway: 'National D-Type Work Visa / Poland.Business Harbour',
    avgSalaryEUR: '€45,000 - €65,000',
    costOfLivingIndex: 42,
    processingTimeMonths: 1.5,
    sponsorshipProbability: 'High',
    topDemandRoles: ['Java Developer', 'React Frontend Specialist', 'QA Engineer'],
  },
  {
    country: 'Netherlands',
    flag: '🇳🇱',
    eligibilityScore: 82,
    visaPathway: 'Highly Skilled Migrant (KM) Visa + 30% Tax Facility',
    avgSalaryEUR: '€75,000 - €105,000',
    costOfLivingIndex: 76,
    processingTimeMonths: 1,
    sponsorshipProbability: 'High',
    topDemandRoles: ['Full Stack Engineer', 'Cloud Architect', 'Product Designer'],
  },
  {
    country: 'Czech Republic',
    flag: '🇨🇿',
    eligibilityScore: 85,
    visaPathway: 'Employee Card / EU Blue Card',
    avgSalaryEUR: '€42,000 - €58,000',
    costOfLivingIndex: 48,
    processingTimeMonths: 2.5,
    sponsorshipProbability: 'Medium',
    topDemandRoles: ['C++ Systems Engineer', 'Python Backend', 'Cybersecurity'],
  },
  {
    country: 'Lithuania',
    flag: '🇱🇹',
    eligibilityScore: 90,
    visaPathway: 'Startup Visa & EU Skilled Worker Permit',
    avgSalaryEUR: '€38,000 - €54,000',
    costOfLivingIndex: 40,
    processingTimeMonths: 1,
    sponsorshipProbability: 'High',
    topDemandRoles: ['Fintech Full Stack', 'Mobile React Native', 'Data Engineer'],
  },
  {
    country: 'Slovakia',
    flag: '🇸🇰',
    eligibilityScore: 86,
    visaPathway: 'Temporary Residence for Employment',
    avgSalaryEUR: '€36,000 - €50,000',
    costOfLivingIndex: 44,
    processingTimeMonths: 2,
    sponsorshipProbability: 'Medium',
    topDemandRoles: ['Backend Java Developer', 'Frontend Angular/React', 'DevOps'],
  },
];
